# -*- coding: utf-8 -*-
"""DAP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PRT5ac4EujFby7DY133zfqg2dyiimd3a
"""

import numpy as np
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]


result = [[0,0,0],
        [0,0,0],
        [0,0,0]]
for i in range(len(X)):
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]

+for r in result:
    print(r)









import numpy as np
#creating arrays
arr=np.array([1,2,3,4,5])
print(arr)
zeros_arr=np.zeros((3,3),dtype=int)
print(zeros_arr)

ones_arr=np.ones((2,2),dtype=int)
print(ones_arr)

arange_arr=np.arange(10)
print(arange_arr)

#array manupulation
reshaped_arr=arr.reshape(5,1)
print(reshaped_arr)

sliced_arr=arr[2:4]
print(sliced_arr)

arr1=np.array([1,2,3])
arr2=np.array([7,8,9])
print(arr1+arr2)
#r=arr1+arr2
#print(r)
c=np.vstack(arr1+arr2)
print(c)
e=np.array([[1,2,3],[4,5,6]])
b=e.T
print(b)
f=np.split(e,2)
print(f)

arr1=np.array([1,2,3])
res=arr1+3
print(res)


a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
print(a2)
b1=np.dot(a1,a2)
print(b1)
print("\n","\n")
a1=np.linalg.eig(a2)
print(a1)
c1=np.array([[1,2,3],[4,5,6]])
print(c1)
c2=np.array([[1,2,3],[4,5,6]])
print(c2)
c3=np.sum(c1+c2)
print(c3)

e1=np.array([[1,2,3],[4,4,6]])
a=np.sum(e1,axis=0)
print(a)
b=np.sum(e1,axis=1)
print(b)
#variance
a1=np.array([1,2])
print(a1)
a2=np.mean(a1)
print(a2)
a3=np.median(a1)
print(a3)
a4=np.var(a1)
print(a4)

a1=np.array([1,2,3,4,5])
print(a1)
a2=np.mean(a1)
print(a2)
a3=np.median(a1)
print(a3)
a4=np.var(a1)
print(a4)
a5=np.std(a1)
print(a5)



data=np.loadtxt("/content/file.txt",dtype=int)
print(data)
data=np.savetxt("/content/file1.txt",data)
print(data)

import matplotlib.pyplot as plt
a=np.array([1,2,3,4,5,6,7,8,9,10])
plt.plot(a)

import pandas as pd
a=["Jwalitha","Ramya","Durga","Jahnavi","Lahari","Sunny","Dhanush"]
r=pd.Series(a,index=[67,43,44,89,34,45,33])
print(r)

df=pd.read_csv("/content/netflix_revenue_updated.csv")
print(df)

df=pd.read_csv("/content/netflix_revenue_updated.csv",sep=" ")
print(df)
df=pd.read_csv("/content/netflix_revenue_updated.csv")
mv=df["Netflix Streaming Memberships "].mean()
df=df.fillna(mv)
print(df)


#df=pd.read_csv("/content/file.txt",sep=" ")
#print(df)

df=pd.read_excel("/content/batsman-stats.xlsx")
print(df)

df=pd.read_excel("/content/salesworkload.xlsx")
print(df)


df=pd.read_excel("/content/salesworkload.xlsx",sheet_name=1)
print(df)

df=pd.read_csv("/content/file.txt",sep=" ")
print(df.loc[1])

df=df.drop_duplicates()
print(df)



import pandas as pd
df=pd.read_csv("/content/netflix_revenue_updated.csv")
print(df)
a=df.head(5)
b=df.tail(5)
total_data=pd.concat([a,b],axis=0)
total_data.to_csv("c")
print(total_data.groupby(['EMEA  Members'])['LATM Members'].count())

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import matplotlib.pyplot as plt
runs=np.array([100,50,91,78,89,25,34,19,9,10])
w=np.array([1,0,2,0,3,7,8,9,7,5])
plt.plot(runs,w,color='blue')
plt.title('IndvsAus_score')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
tiger=np.linspace(-2*np.pi,2*np.pi,50)
print(tiger)
plt.plot(tiger,np.sin(tiger),color='black')
#plt.plot(x,y,,color,label....)
plt.title("sin(x)")

import numpy as np
import matplotlib.pyplot as plt
overs=np.arange(5,50,5)
overs_a=np.arange(5,30,5)
runs_i=np.array([25,51,84,131,160,189,220,250,267])
runs_a=np.array([15,41,94,110,151])
wickets=np.array([12,32,96])
plt.subplot(2,1,2)
plt.plot(overs,runs_i,color='blue',label='India')
plt.subplot(2,1,1)
plt.plot(overs_a,runs_a,color='red',label='Aus')
plt.legend(loc='best')
plt.show()

import matplotlib.pyplot as plt
a=[230,560,780,127,128]
b=[200,160,270,127,400]
years=[1,2,3,4]
profit_a=[(a[i]-a[i-1]) for i in range(1,len(a))]
profit_b=[(b[i]-b[i-1]) for i in range(1,len(b))]
plt.subplot(2,1,2)
plt.plot(years,profit_a,color='hotpink',linewidth='3',label='CompanyA',marker='.',ms='15')
plt.legend(loc='best')
plt.subplot(2,1,1)
plt.plot(years,profit_b,color='black',linestyle='dotted',label='CompanyB',marker='h')
plt.legend(loc='best')

a=np.array([25,60,5,10])
labe=["AIML","PYTHON","PANDAS","NUMPY"]
plt.pie(a,labels=labe,colors=c)
c=["yellow","pink","skyblue","violet"]
plt.show()

a=np.array([25,60,5,10])
labe=["AIML","PYTHON","PANDAS","NUMPY"]
c=["hotpink","yellow","skyblue","violet"]
explo=[0.2,0,0,0]
plt.pie(a,labels=labe,explode=explo,colors=c,startangle=180,textprops={'fontsize':32})
plt.show()

import numpy as np
import pandas as pd
df=pd.read_csv("/content/city_temperature.csv")
print(df)
average_temperature=df['AvgTemperature'].mean()
highest_temperature=df['AvgTemperature'].max()
lowest_temperature=df['AvgTemperature'].min()
threshold=30
days_above_threshold=df[df['AvgTemperature']>threshold].shape[0]
print("Average temperature for the month:",average_temperature)
print("Highest temperature for the month:",highest_temperature)
print("Lowest temperature for the month:",lowest_temperature)
print("Number of days where temperatures exceeded",threshold,"degrees Celsius:",days_above_threshold)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("/content/Book2.csv")
print("Least Temperature Noted in January:\n",df.min())
print("Heightest Temperature Noted in January:\n",df.max())
c=df['JAN'].mean()
print("Average Temperature in the Month of January",c)
year = np.arange(1901,1950)
temp=np.array([22.4,24.93,23.44,22.5,22,22.28,24.46,23.57,22.67,23.24,23.22,23.7,23.71,24.42,22.6,24.13,23.68,22.06,23.32,22.87,23.57,22.96,23.25,22.84,22.56,23.54,23.23,23.33,23.05,22.6,24.57,24.13,22.85,22.76,22.28,23.1,23.34,22.95,23.61,23.79,23.18,22.99,22.97,23.17,22.38,24.41,22.61,22.87,24.31])
plt.plot(year,temp,color='black',label="x-axis:year\ny-axis:temp")
plt.legend(loc='best')
plt.title("Temperatures in January")
plt.show()