# -*- coding: utf-8 -*-
"""seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-nHk1SiLtiEhHFV3tDAB90wXJlGBhMpk
"""

pip install seaborn

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
sns.scatterplot(x="total_bill",y="tip",data=tips)
plt.title("Scatter plot of Total Bill vs.Tip")
plt.xlabel("Total Bill($)")
plt.ylabel("Tip($)")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv("/content/Book2.csv")
tips=sns.load_dataset("tips")
sns.scatterplot(x="total_bill",y="tip",data=tips)
plt.title("Scatter plot of Total Bill vs.Tip")
plt.xlabel("Total Bill($)")
plt.ylabel("Tip($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Load the anscombe dataset
anscombe = sns.load_dataset("anscombe")

# Display the first few rows of the dataset to understand its structure
print(anscombe.head())

# Plot the four datasets in the anscombe dataset
sns.set(style="ticks")
sns.lmplot(x="x", y="y", col="dataset", hue="dataset", data=anscombe,
           col_wrap=2, ci=None, palette="muted", height=4,
           scatter_kws={"s": 50, "alpha": 1})
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
sns.violinplot(x="day",y="total_bill",data=tips)
sns.scatterplot(x="total_bill",y="tip",data=tips)
plt.title("Distribution of total Bill vs.Tip")
plt.xlabel("Day of the week")
plt.ylabel("Total Bill($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
iris=sns.load_dataset("iris")
correlation_matrix=iris.corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("correlation heatmap of Iris Dataset")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
iris=sns.load_dataset("planets")
print(iris.head())
correlation_matrix=iris.corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("correlation heatmap of planet Dataset")
plt.show()

